name: darin
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/TamasBarta/darin

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.10

