name: darin
description: Dependency Injection oversimplified. Inspired by Koin, with focus on scopes. 
version: 0.1.1
repository: https://github.com/TamasBarta/darin

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.10

